# Generated by Django 4.1.5 on 2023-05-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_cliente', models.CharField(max_length=30)),
                ('email_cliente', models.CharField(max_length=20)),
                ('num_telefonico_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('cantidad_productos', models.IntegerField()),
                ('total_compra', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcracks.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('rut_empleado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_empleado', models.CharField(max_length=30)),
                ('email_empleado', models.CharField(max_length=20)),
                ('num_telefonico_empleado', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcracks.compra')),
            ],
        ),
    ]
